Update requirements.txt
error: Couldn't parse requirement in `requirements.txt` at position 71

  Caused by: no such comparison operator "=", must be one of ~= == != <= >= < > ===

streamlit=1.31.1

         ^^^^^^^